### ISSUE TITLE
Output column names

### ISSUE THREAD

**Issue by colindaven** [esteinig/vircov#13]
Looks very interesting. Did I miss the output column names somewhere ?

```
gi_1070105496_ref_NC_031108.1__Propionibacterium_phage_PFR2,_complete_genome           2   2    2    132   0   0.0000
gi_1070125494_ref_NC_031129.1__Salmonella_phage_SJ46,_complete_genome                  2   2    2    128   0   0.0000
gi_110645916_ref_NC_001401.2__Adeno-associated_virus_-_2,_complete_genome              1   2    2    67    0   0.0000

```
Thanks

**Comment by esteinig** [comment]
Ah sorry haven't documented everything properly yet, you can add `-t/--table` to get better formatted output (let me know if it's mangled, still gotta fine tune that table format)

**Comment by esteinig** [comment]
And `-p/--covplot` if a `--fasta` file is provided to get some basic (approximate) coverage plots in the terminal.

**Comment by esteinig** [comment]
Also note there are default options for minimum query alignment length (50 bp) and minimum mapping quality (30) on by default at the moment. You can set `--min-len / --min-mapq` to zero to deactivate those.

**Comment by colindaven** [comment]
Ok, thanks for the info, I'll have another go at it and write some scripts.

**Comment by esteinig** [comment]
If you are planning to integrate `vircov` into a pipeline, maybe hold out for the next release as the input command line arguments are going to change (due to adding SAM/BAM support). Should have that out in a couple of days!

I forgot there is also one empty column at the end - `-v/--verbose` will add whitespace separated tags into that column, one for each coverage region in the format `<start of region>:<stop of region>:<number of alignments in the region>`

**Comment by colindaven** [comment]
Ok,  no worries. We're just testing, not writing a formal pipeline, and that's probably the extent of use at the moment. It's better than other efforts we've seen, but alignment vs viruses is definitely an unsolved problem. Coverage is generally a huge issue, as is genome size and specific mappings - as I'm sure you know.

**Comment by esteinig** [comment]
Yeah definitely, we are trying to address the same issues and see what sticks (as you can see). This little tool is meant to be more experimental at this stage, rather than a definitive solution to a really hard problem. Saw your nice efforts on the Wochenende pipeline, very cool and a fitting name :)
